alter table "public"."farmers" drop constraint "farmers_market_fkey";

create table "public"."farmer_markets" (
    "farmer_id" integer generated by default as identity not null,
    "market_id" bigint not null
);


alter table "public"."farmer_markets" enable row level security;

alter table "public"."farmers" drop column "market_id";

CREATE UNIQUE INDEX farmer_markets_pkey ON public.farmer_markets USING btree (farmer_id, market_id);

CREATE UNIQUE INDEX markets_name_key ON public.markets USING btree (name);

alter table "public"."farmer_markets" add constraint "farmer_markets_pkey" PRIMARY KEY using index "farmer_markets_pkey";

alter table "public"."farmer_markets" add constraint "farmer_markets_farmer_id_fkey" FOREIGN KEY (farmer_id) REFERENCES farmers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."farmer_markets" validate constraint "farmer_markets_farmer_id_fkey";

alter table "public"."farmer_markets" add constraint "farmer_markets_market_id_fkey" FOREIGN KEY (market_id) REFERENCES markets(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."farmer_markets" validate constraint "farmer_markets_market_id_fkey";

alter table "public"."markets" add constraint "markets_name_key" UNIQUE using index "markets_name_key";

create or replace view "public"."product_farmers_markets" as  SELECT p.name AS product,
    f.name AS farmer,
    m.name AS market
   FROM (((products p
     JOIN farmers f ON ((p.farmer_id = f.id)))
     JOIN farmer_markets fm ON ((f.id = fm.farmer_id)))
     JOIN markets m ON ((fm.market_id = m.id)))
  ORDER BY p.name;


grant delete on table "public"."farmer_markets" to "anon";

grant insert on table "public"."farmer_markets" to "anon";

grant references on table "public"."farmer_markets" to "anon";

grant select on table "public"."farmer_markets" to "anon";

grant trigger on table "public"."farmer_markets" to "anon";

grant truncate on table "public"."farmer_markets" to "anon";

grant update on table "public"."farmer_markets" to "anon";

grant delete on table "public"."farmer_markets" to "authenticated";

grant insert on table "public"."farmer_markets" to "authenticated";

grant references on table "public"."farmer_markets" to "authenticated";

grant select on table "public"."farmer_markets" to "authenticated";

grant trigger on table "public"."farmer_markets" to "authenticated";

grant truncate on table "public"."farmer_markets" to "authenticated";

grant update on table "public"."farmer_markets" to "authenticated";

grant delete on table "public"."farmer_markets" to "service_role";

grant insert on table "public"."farmer_markets" to "service_role";

grant references on table "public"."farmer_markets" to "service_role";

grant select on table "public"."farmer_markets" to "service_role";

grant trigger on table "public"."farmer_markets" to "service_role";

grant truncate on table "public"."farmer_markets" to "service_role";

grant update on table "public"."farmer_markets" to "service_role";

create policy "public_select_policy"
on "public"."farmer_markets"
as permissive
for select
to public
using (true);



